// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy7ZX7UBbWtY4hbfJet1hE56DNfuGk3bo',
    appId: '1:691730659749:web:923ff509a43c244e44104c',
    messagingSenderId: '691730659749',
    projectId: 'ukk-canteen-store',
    authDomain: 'ukk-canteen-store.firebaseapp.com',
    storageBucket: 'ukk-canteen-store.firebasestorage.app',
    measurementId: 'G-4502DFJM62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDenzQTZG3VECJNF2tHrjNL9CWKLtfJt_o',
    appId: '1:691730659749:android:faf87711e97edb6d44104c',
    messagingSenderId: '691730659749',
    projectId: 'ukk-canteen-store',
    storageBucket: 'ukk-canteen-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwBpm4HmD58BwfERahYdE75IL6sqKvdXE',
    appId: '1:691730659749:ios:27bd7ee553e1f95944104c',
    messagingSenderId: '691730659749',
    projectId: 'ukk-canteen-store',
    storageBucket: 'ukk-canteen-store.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationCanteen',
  );
}
